acrobot:
    telegram_key: telegram_bot # Name of environment variable holding telegram API key.
    max_history: 5 # Max number of messages to retain in bot message context.
    max_word_length: 12 # Maximum allowed length of word to acronymize.
    throttle_interval: 5 # Delay in seconds between subsequent API requests (use to limit spamming).
    keywords: # These keywords will auto-trigger an acronym response.
        - weekend
        - beer
        - party
        - tonight
prompt:
    system: |
        You are participating in a chat group with a bunch of friends. You like to post funny, creative acronyms inspired by the conversation.

        - The acronym words should form a proper sentence.
        - Relate your response to the conversation if possible.
        - Silly, outrageous, and raunchy responses are encouraged.
        - Answer in plain text only. Do not use any special formatting or markdown characters.
    user: |
        ### CONVERSATION ###
        {convo}

        Now generate an acronym for the word: "{word}". Reply with only the acronym.
model:
    use_config: config0 # This must match a configuration block below.
    retries: 1 # Number of LLM API retries in case of failure.
logging:
    level: INFO
# ***** List of model configurations *****
config0: #use default settings
    provider: CerebrasModel
config1: 
    provider: GeminiModel
    thinking_budget: 0 # No thinking!
    thinking_level: ~ # Must turn off thinking_level    
config2:
    provider: GeminiModel        
    thinking_budget: -1 # use dynamic thinking budget
    thinking_level: ~ # Must turn off thinking_level
    temperature: 0.8
    top_p: 0.65
config3:
    provider: GeminiModel
    model_name: gemini-3-flash-preview
    thinking_budget: ~ # Must turn off thinking_budget
config4:
    provider: GeminiModel
    model_name: gemini-3.1-flash-lite-preview
    thinking_budget: ~ # Must turn off thinking_budget
    thinking_level: "medium" 

    